Regenerate initrd if missing
Fix #136

Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/sdbootutil b/sdbootutil
--- a/sdbootutil
+++ b/sdbootutil
@@ -599,6 +599,7 @@ reuse_initrd()
 		local k v
 		while read -r k v; do
 			[ "$k" = 'initrd' ] || continue
+			[ -f "${boot_root}$v" ] || continue
 			log_info "found existing initrd $v"
 			dstinitrd+=("$v")
 		done < "$conf"
@@ -1652,7 +1653,7 @@ pcrlock_manual_raw()
 {
 	local pcr="$1"
 	local pcrlock="$2"
-	local initrd="$3"
+	local element="$3"
 
 	echo -n '{"records":[{"pcr":'"$pcr"',"digests":[' > "$pcrlock"
 	local separator=0
@@ -1661,7 +1662,7 @@ pcrlock_manual_raw()
 		[ "$separator" = "0" ] || echo -n "," >> "$pcrlock"
 		separator=1
 		hash "${a}sum" || continue
-		read -r digest _ < <("${a}sum" "$initrd")
+		read -r digest _ < <("${a}sum" "$element")
 		echo -n '{"hashAlg":"'"$a"'","digest":"'"$digest"'"}' >> "$pcrlock"
 	done
 	echo ']}]}' >> "$pcrlock"
@@ -1797,12 +1798,16 @@ pcrlock_sdboot()
 	# pcrlock standards
 	# TODO: move to kernel-TYPE-pcrlock.rpm
 	local n=0
-	while read -r i; do
+	while read -r linux; do
+		[ -f "${boot_root}$linux" ] || {
+			log_info "Missing ${boot_root}$linux, ignoring entry for prediction"
+			continue
+		}
 		n=$((n+1))
 		pcrlock \
 			lock-pe \
 			--pcrlock=/var/lib/pcrlock.d/650-kernel-efi-application.pcrlock.d/linux-"$n".pcrlock \
-			"${boot_root}/$i"
+			"${boot_root}/$linux"
 	done < <(jq --raw-output 'map(.linux) | unique | .[]' "$entryfile")
 
 	# Join the cmdline and the initrd in a single component
@@ -1810,6 +1815,10 @@ pcrlock_sdboot()
 	n=0
 	while read -r cmdline; do
 		read -r initrd
+		[ -f "${boot_root}$initrd" ] || {
+			log_info "Missing ${boot_root}$initrd, ignoring entry for prediction"
+			continue
+		}
 		n=$((n+1))
 		pcrlock_sdboot_cmdline_initrd "initrd=$cmdline" "${boot_root}$initrd" "$n"
 	done < <(jq --raw-output '.[] | ([(.initrd[0] | sub("/"; "\\"; "g")), .options] | join(" ")), .initrd[0]' "$entryfile"
@@ -1860,11 +1869,19 @@ pcrlock_grub2_bls()
 	mkdir -p /var/lib/pcrlock.d/650-grub2-bls-entry-cmdline.pcrlock.d
 	n=0
 	while read -r options; do
-		read -r kernel
+		read -r linux
 		read -r initrd
+		[ -f "${boot_root}$linux" ] || {
+			log_info "Missing ${boot_root}$linux, ignoring entry for prediction"
+			continue
+		}
+		[ -f "${boot_root}$initrd" ] || {
+			log_info "Missing ${boot_root}$initrd, ignoring entry for prediction"
+			continue
+		}
 		n=$((n+1))
-		pcrlock_grub2_bls_cmdline "linux ${grub2_bls_drive}$kernel $options" \
-					  "${grub2_bls_drive}$kernel $options" \
+		pcrlock_grub2_bls_cmdline "linux ${grub2_bls_drive}$linux $options" \
+					  "${grub2_bls_drive}$linux $options" \
 					  "initrd ${grub2_bls_drive}$initrd" "$n"
 	done < <(jq --raw-output '.[] | .options, .linux, .initrd[0]' "$entryfile")
 
@@ -1877,11 +1894,11 @@ pcrlock_grub2_bls()
 	n=0
 	if [ "$SDB_ADD_INITIAL_COMPONENT" = "1" ]; then
 		while read -r options; do
-			read -r kernel
+			read -r linux
 			read -r initrd
 			n=$((n+1))
-			pcrlock_grub2_bls_cmdline "linux ${grub2_bls_drive}$kernel $options" \
-						  "${grub2_bls_drive}$kernel $options" \
+			pcrlock_grub2_bls_cmdline "linux ${grub2_bls_drive}$linux $options" \
+						  "${grub2_bls_drive}$linux $options" \
 						  "initrd ${grub2_bls_drive}$initrd" "0-$n"
 		done < <(jq --raw-output '.[] | .options, .linux, .initrd[0]' "$initialentryfile")
 	fi
@@ -1889,20 +1906,22 @@ pcrlock_grub2_bls()
 	# Join the kernel and the initrd in a single component
 	mkdir -p /var/lib/pcrlock.d/710-grub2-bls-kernel-initrd-entry.pcrlock.d
 	n=0
-	while read -r kernel; do
+	while read -r linux; do
 		read -r initrd
+		[ -f "${boot_root}$linux" ] || continue
+		[ -f "${boot_root}$initrd" ] || continue
 		n=$((n+1))
-		pcrlock_grub2_bls_kernel_initrd "$boot_root$kernel" "$boot_root$initrd" "$n"
+		pcrlock_grub2_bls_kernel_initrd "${boot_root}$linux" "${boot_root}$initrd" "$n"
 	done < <(jq --raw-output '.[] | .linux, .initrd[0]' "$entryfile")
 
 	# Generate variation for 710-grub2-bls-kernel-initrd-entry for the
 	# same reason than before.
 	n=0
 	if [ "$SDB_ADD_INITIAL_COMPONENT" = "1" ]; then
-		while read -r kernel; do
+		while read -r linux; do
 			read -r initrd
 			n=$((n+1))
-			pcrlock_grub2_bls_kernel_initrd "$tmpdir$kernel" "$tmpdir$initrd" "0-$n"
+			pcrlock_grub2_bls_kernel_initrd "${tmpdir}$linux" "${tmpdir}$initrd" "0-$n"
 		done < <(jq --raw-output '.[] | .linux, .initrd[0]' "$initialentryfile")
 	fi
 }
