Keep original prediction for pcrlock aligment
Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/sdbootutil b/sdbootutil
--- a/sdbootutil
+++ b/sdbootutil
@@ -1859,6 +1859,31 @@ backup_initial_components()
 	cp -a "$boot_root/." "$tmpdir"
 }
 
+shift_component()
+{
+	local component="$1"
+
+	dbg "Shifting component $component"
+	[ -d "/var/lib/pcrlock.d/$component.pcrlock.d" ] || {
+		dbg "The component is not a directory or is missing"
+		return 0
+	}
+
+	# Move the current variations of a component with
+	# `shift-N-*.pcrlock` prefix.  The systemd-pcrlock tool will
+	# manage duplicates, so with several .pcrlock files share the
+	# same hashes, only one will be used to build the policy,
+	# without increasing the combiations (PolicyOR limitation)
+	local cname
+	for element in /var/lib/pcrlock.d/"$component".pcrlock.d/*.pcrlock; do
+		cname="$(basename "$element")"
+		[[ "$cname" != shift-* ]] || continue
+		[ ! -e "/var/lib/pcrlock.d/$component.pcrlock.d/shift-$cname" ] || continue
+		dbg "$element -> /var/lib/pcrlock.d/$component.pcrlock.d/shift-$cname"
+		mv "$element" "/var/lib/pcrlock.d/$component.pcrlock.d/shift-$cname"
+	done
+}
+
 pcrlock_manual_raw()
 {
 	local pcr="$1"
@@ -1895,6 +1920,7 @@ pcrlock_sdboot_cmdline_initrd()
 		lock-kernel-initrd \
 		--pcrlock="$tmpdir/initrd.pcrlock" \
 		"$initrd" 2> /dev/null || pcrlock_manual_raw 9 "$tmpdir/initrd.pcrlock" "$initrd"
+	mkdir -p /var/lib/pcrlock.d/710-kernel-cmdline-initrd-entry.pcrlock.d
 	jq --slurp '{"records": [.[].records[0]]}' \
 	   "$tmpdir/cmdline.pcrlock" \
 	   "$tmpdir/initrd.pcrlock" \
@@ -1933,6 +1959,7 @@ pcrlock_grub2_bls_kernel_initrd()
 			"$element" 2> /dev/null || pcrlock_manual_raw 9 "$tmpdir/element-$n.pcrlock" "$element"
 		locks+=("$tmpdir/element-$n.pcrlock")
 	done
+	mkdir -p /var/lib/pcrlock.d/710-grub2-bls-kernel-initrd-entry.pcrlock.d
 	jq --slurp '{"records": [.[].records[0]]}' \
 	   "${locks[@]}" \
 	   > "/var/lib/pcrlock.d/710-grub2-bls-kernel-initrd-entry.pcrlock.d/kernel-initrd-$suffix.pcrlock"
@@ -1960,6 +1987,7 @@ pcrlock_grub2_bls_cmdline()
 		locks+=("$tmpdir/line-$n.pcrlock")
 		rm "$tmpdir/line"
 	done
+	mkdir -p /var/lib/pcrlock.d/650-grub2-bls-entry-cmdline.pcrlock.d
 	jq --slurp '{"records": [.[].records[0]]}' \
 	   "${locks[@]}" \
 	   > "/var/lib/pcrlock.d/650-grub2-bls-entry-cmdline.pcrlock.d/cmdline-$suffix.pcrlock"
@@ -1984,7 +2012,7 @@ pcrlock_grub2_bls_entry_files()
 			"$base/loader/entries/$i"
 		locks+=("$tmpdir/entry-$n.pcrlock")
 	done < <(ls -U "$base"/loader/entries)
-
+	mkdir -p /var/lib/pcrlock.d/643-grub2-bls-entry-files.pcrlock.d
 	jq --slurp '{"records": [.[].records[0]]}' \
 	   "${locks[@]}" \
 	   > "/var/lib/pcrlock.d/643-grub2-bls-entry-files.pcrlock.d/generated$suffix.pcrlock"
@@ -1998,15 +2026,17 @@ pcrlock_sdboot()
 	# 641-sdboot-loader-conf.pcrlock is not part of the pcrlock
 	# standards
 	if [ -e "${boot_root}/loader/loader.conf" ]; then
+		shift_component 641-sdboot-loader-conf
 		pcrlock \
 			lock-raw "${boot_root}/loader/loader.conf" \
 			--pcr=5 \
-			--pcrlock=/var/lib/pcrlock.d/641-sdboot-loader-conf.pcrlock
+			--pcrlock=/var/lib/pcrlock.d/641-sdboot-loader-conf.pcrlock.d/generated.pcrlock
 	fi
 
 	# 650-kernel-efi-application.pcrlock is not part of the
 	# pcrlock standards
 	# TODO: move to kernel-TYPE-pcrlock.rpm
+	shift_component 650-kernel-efi-application
 	local n=0
 	local -A kernels
 	while read -r linux; do
@@ -2028,7 +2058,8 @@ pcrlock_sdboot()
 	done < <(jq --raw-output 'sort_by(.priority) | map(.linux) | .[]' "$entryfile")
 
 	# Join the cmdline and the initrd in a single component
-	mkdir -p /var/lib/pcrlock.d/710-kernel-cmdline-initrd-entry.pcrlock.d
+	shift_component 710-kernel-cmdline-initrd-entry
+	shift_component 710-kernel-cmdline-boot-loader
 	n=0
 	while read -r cmdline; do
 		read -r initrd
@@ -2067,15 +2098,16 @@ pcrlock_grub2_bls()
 	# 641-grub2-bls-grubenv.pcrlock is not part of the pcrlock
 	# standards
 	if [ -e "${boot_root}${boot_dst}/grubenv" ]; then
+		shift_component 641-grub2-bls-grubenv
 		pcrlock \
 			lock-raw "${boot_root}${boot_dst}/grubenv" \
 			--pcr=9 \
-			--pcrlock=/var/lib/pcrlock.d/641-grub2-bls-grubenv.pcrlock
+			--pcrlock=/var/lib/pcrlock.d/641-grub2-bls-grubenv.pcrlock.d/generated.pcrlock
 	fi
 
 	# 643-grub2-bls-entry-files.pcrlock is not part of the pcrlock
 	# standards
-	mkdir -p /var/lib/pcrlock.d/643-grub2-bls-entry-files.pcrlock.d
+	shift_component 643-grub2-bls-entry-files
 	pcrlock_grub2_bls_entry_files
 	if [ "$SDB_ADD_INITIAL_COMPONENT" = "1" ]; then
 		pcrlock_grub2_bls_entry_files "0" "$tmpdir"
@@ -2089,7 +2121,7 @@ pcrlock_grub2_bls()
 	grub2_bls_drive="(hd0,gpt$partno)"
 
 	# Join linux, initrd and cmdline in a single pcrlock file
-	mkdir -p /var/lib/pcrlock.d/650-grub2-bls-entry-cmdline.pcrlock.d
+	shift_component 650-grub2-bls-entry-cmdline
 	n=0
 	while read -r options; do
 		read -r linux
@@ -2131,7 +2163,7 @@ pcrlock_grub2_bls()
 	fi
 
 	# Join the kernel and the initrd in a single component
-	mkdir -p /var/lib/pcrlock.d/710-grub2-bls-kernel-initrd-entry.pcrlock.d
+	shift_component 710-grub2-bls-kernel-initrd-entry
 	n=0
 	while read -r linux; do
 		read -r initrd
@@ -2157,6 +2189,19 @@ pcrlock_grub2_bls()
 clean_pcrlock_d()
 {
 	[ -d /var/lib/pcrlock.d ] || return 0
+
+	# Remove the shifted measurements since the last reboot.  They
+	# are used to link the current components with the event log,
+	# so pcrlock can work with the aligments.  For example, if a
+	# file gets replaced (loader.conf) the new measurement cannot
+	# be found in the event log, as contains the old hash, making
+	# the aligment fail.
+	local last_reboot
+	last_reboot="$(systemctl show --property ActiveEnterTimestamp init.scope)"
+	last_reboot="${last_reboot#ActiveEnterTimestamp=}"
+	local minutes=$((1 + ($(date +%s) - $(date -d"$last_reboot" +%s)) / 60))
+	dbg "Cleaning shifted measurements older than $minutes minutes"
+	find /var/lib/pcrlock.d -name 'shift-*.pcrlock' -type f -cmin +"$minutes" -delete
 
 	# Remove older (1 week) generated measurements.  This will
 	# keep the predictions at minimum and decrease the
@@ -2195,6 +2240,7 @@ generate_tpm2_predictions_pcrlock()
 
 	# 630-shim-efi-application is not part of the pcrlock standards
 	# TODO: move to shim-pcrlock.rpm
+	shift_component 630-shim-efi-application
 	local entry="shim.efi"
 	[ -f "${boot_root}${boot_dst}/${entry}" ] || entry="BOOT${firmware_arch^^}.EFI"
 	pcrlock \
@@ -2206,6 +2252,7 @@ generate_tpm2_predictions_pcrlock()
 	# standards
 	# This is measuring the systemd-boot EFI binary (named grub.efi)
 	# TODO: move to systemd-boot-pcrlock.rpm
+	shift_component 640-boot-loader-efi-application
 	pcrlock \
 		lock-pe \
 		--pcrlock=/var/lib/pcrlock.d/640-boot-loader-efi-application.pcrlock.d/generated.pcrlock \
