Unify PCR selection
Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/sdbootutil b/sdbootutil
--- a/sdbootutil
+++ b/sdbootutil
@@ -1297,47 +1297,29 @@ generate_tpm2_predictions_pcrlock()
 	[ -e /var/lib/systemd/pcrlock.json ] && cp /var/lib/systemd/pcrlock.json "${boot_root}${sdboot_dst}"
 }
 
-get_pcrs() {
-	local pcrs
-	local jq_pcr='.tokens[]|select(.type == "systemd-tpm2")|."tpm2_pubkey_pcrs"|join(",")'
-	# We can have multiple devices, each one of them with
-	# different PCRs
-	while read -r dev; do
-		pcrs=$(cryptsetup luksDump --dump-json-metadata "$dev" | jq -r "$jq_pcr")
-		[ -z "$pcrs" ] || echo "$pcrs"
-	done <<<$(blkid -t TYPE=crypto_LUKS -o device)
-}
-
 # TODO: Maybe share this code outside
 generate_tpm2_predictions_pcr_oracle()
 {
 	local entry
-	local all_pcrs
+	local pcrs="$1"
 
 	# Select the affected entries
 	select_entries_for_prediction
 
-	all_pcrs=$(get_pcrs)
-	[ -z "$all_pcrs" ] || rm -f /etc/systemd/tpm2-pcr-signature.json
+	[ -z "$pcrs" ] || rm -f /etc/systemd/tpm2-pcr-signature.json
 
-	# We make as many predictions as |all_pcrs| * |entries| to
-	# cover all the combinations.  pcr-oracle is smart to include
-	# the entry only one time, so we will not have duplications.
-	# This is a step for multi device configurations.
-	for pcrs in $all_pcrs; do
-		while read -r entry; do
-			log_info "Generate prediction for $entry with PCRs $pcrs"
-			if ! pcr-oracle \
-				--private-key /etc/systemd/tpm2-pcr-private-key.pem \
-				--from eventlog \
-				--output /etc/systemd/tpm2-pcr-signature.json \
-				--target-platform=systemd \
-				--boot-entry "${entry}" \
-				sign "$pcrs"; then
-				err "Failed to install TPM predictions for ${entry_id}"
-			fi
-		done < <(jq -r '.[]|.id' "$entryfile")
-	done
+	while read -r entry; do
+		log_info "Generate prediction for $entry with PCRs $pcrs"
+		if ! pcr-oracle \
+		     --private-key /etc/systemd/tpm2-pcr-private-key.pem \
+		     --from eventlog \
+		     --output /etc/systemd/tpm2-pcr-signature.json \
+		     --target-platform=systemd \
+		     --boot-entry "${entry}" \
+		     sign "$pcrs"; then
+		    err "Failed to install TPM predictions for ${entry}"
+		fi
+	done < <(jq -r '.[]|.id' "$entryfile")
 
 	# Publish the assets in the ESP, so can be imported by
 	# dracut-pcr-signature
@@ -1363,7 +1345,7 @@ generate_tpm2_predictions()
 	if is_pcrlock; then
 		generate_tpm2_predictions_pcrlock "${FDE_SEAL_PCR_LIST}"
 	elif is_pcr_oracle; then
-		generate_tpm2_predictions_pcr_oracle
+		generate_tpm2_predictions_pcr_oracle "${FDE_SEAL_PCR_LIST}"
 	fi
 }
 
