Try to to sync with target

diff --git a/sdbootutil b/sdbootutil
--- a/sdbootutil
+++ b/sdbootutil
@@ -20,7 +20,7 @@ arg_all_entries=
 arg_no_variables=
 arg_no_reuse_initrd=
 arg_no_random_seed=
-no_snapshots=0
+have_no_snapshots=
 # for x in vmlinuz image vmlinux linux bzImage uImage Image zImage; do
 image=
 
@@ -64,7 +64,6 @@ helpandquit()
 		  --image		Specify Linux kernel file name
 		  --no-variables	Do not update UEFI variables
 		  --no-reuse-initrd	Always regenerate initrd
-		  --no-snapshots	The running system does not support snapshots
 		  -v, --verbose		More verbose output
 		  -h, --help		This screen
 
@@ -216,9 +215,7 @@ is_transactional()
 
 subvol_is_ro()
 {
-	if [ $no_snapshots -eq 1 ]; then
-		return 0
-	fi
+	[ -n "$have_no_snapshots" ] && return 0
 	local subvol="${1:?}"
 	while read -r line; do
 		[ "$line" = "ro=true" ] && return 0
@@ -228,11 +225,8 @@ subvol_is_ro()
 
 detect_parent() {
 	local subvol="$1"
-	if [ $no_snapshots -eq 1 ]; then
-		parent_uuid=""
-	else
-		parent_uuid="$(btrfs subvol show "${subvol#${subvol_prefix}}" | sed -ne 's/\s*Parent UUID:\s*//p')"
-	fi
+	[ -n $have_no_snapshots ] && return 0
+	parent_uuid="$(btrfs subvol show "${subvol#${subvol_prefix}}" | sed -ne 's/\s*Parent UUID:\s*//p')"
 	[ "$parent_uuid" != '-' ] || parent_uuid=
 	[ -n "$parent_uuid" ] || return 0
 	parent_subvol="$(/sbin/btrfs subvol show -u "$parent_uuid" "${subvol#${subvol_prefix}}" | head -1)"
@@ -246,35 +240,32 @@ detect_parent() {
 
 sedrootflags()
 {
-	if [ $no_snapshots -eq 1 ]; then
-		local subvol=""
 	sed -e "s/[ \t]\+/ /g;s/\<\(BOOT_IMAGE\|initrd\)=[^ ]* \?//;s/\<root=[^ ]*/root=UUID=$root_uuid/;tr;:r;:x"
-	else
-		local subvol="${1:?}"
-	fi
+	[ -n "$have_no_snapshots" ] && return 0
+	local subvol="${1:?}"
+	sed -e "s/[ \t]\+/ /g;s/\<\(BOOT_IMAGE\|initrd\)=[^ ]* \?//;s/\<root=[^ ]*/root=UUID=$root_uuid/;tr;:r;s,\<rootflags=subvol=[^ ]*,rootflags=subvol=$subvol,;tx; s,\$, rootflags=subvol=$subvol,;:x"
 	# - delete BOOT_IMAGE= and initrd=
 	# - make sure root= refers to uuid
 	# - replace or add rootflags to point at correct subvolume
-	sed -e "s/[ \t]\+/ /g;s/\<\(BOOT_IMAGE\|initrd\)=[^ ]* \?//;s/\<root=[^ ]*/root=UUID=$root_uuid/;tr;:r;s,\<rootflags=subvol=[^ ]*,rootflags=subvol=$subvol,;tx; s,\$, rootflags=subvol=$subvol,;:x"
+
 }
 
 remove_kernel()
 {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		snapshot=""
-		subvol=""
 	else
 		local snapshot="${1:?}"
-		local subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
 		snapshot="${snapshot%/*}"
 	fi
 	
 	local kernel_version="$2"
-	echo "kerbel_version in remove_kernel: $kernel_version"
 	# local snapshot="${subvol#${subvol_prefix}/.snapshots/}"
-	
-	local id="$entry_token-$kernel_version-$snapshot.conf"
-	echo "id: $id"
+	if [ -n "$have_no_snapshots" ]; then
+		local id="$entry_token-$kernel_version.conf"
+	else
+		local id="$entry_token-$kernel_version-$snapshot.conf"
+	fi
 	run_command_output bootctl unlink "$id"
 
 	# This action will require to update the PCR predictions
@@ -306,9 +297,7 @@ update_snapper()
 
 set_snapper_title_and_sortkey()
 {
-	if [ $no_snapshots -eq 1 ]; then
-		return 0
-	fi
+	[ -n "$have_no_snapshots" ] && return 0
 	snapshot="${1:?}"
 	local type date desc important pre_num
 	local snapshot_info
@@ -334,7 +323,7 @@ set_snapper_title_and_sortkey()
 }
 
 reuse_initrd() {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		local snapshot=""
 		local subvol=""
 	else
@@ -407,7 +396,7 @@ add_version_to_title()
 
 install_kernel()
 {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		local snapshot=""
 		local subvol=""
 	else
@@ -428,9 +417,7 @@ install_kernel()
 	# XXX: fix calling with snapshot instead of subvol
 	local snapshot="${subvol#${subvol_prefix}/.snapshots/}"
 	snapshot="${snapshot%/snapshot}"
-	if [ $no_snapshots -eq 1 ]; then
-		snapshot=""
-	fi
+	[ -n "$have_no_snapshots" ] && snapshot=""
 	local initrd="${src%/*}/initrd"
 
 	mkdir -p "$boot_root${dst%/*}"
@@ -449,13 +436,9 @@ install_kernel()
 	elif ! reuse_initrd "$snapshot" "$subvol"; then
 		local snapshot_dir="/.snapshots/$snapshot/snapshot"
 		local dracut_args=()
-		if [ $no_snapshots -eq 1 ]; then
-			snapshot_dir="/"
-			dracut_args=('--force' '--tmpdir' '/var/tmp' '--add-device' "$root_device")
-		fi
-		
-		if [ "$subvol" != "$root_subvol" ]; then
-			dracut_args=('--sysroot' "${snapshot_dir}" '--tmpdir' '/var/tmp' '--add-device' "$root_device")
+		dracut_args=('--force' '--tmpdir' '/var/tmp' '--add-device' "$root_device")
+		if [ "$subvol" != "$root_subvol" ] && [ -z "$have_no_snapshot" ]; then
+			dracut_args+=('--sysroot' "${snapshot_dir}")
 		fi
 		log_info "generating new initrd"
 
@@ -487,7 +470,7 @@ install_kernel()
 
 	title="${os_release_PRETTY_NAME:-Linux $kernel_version}"
 	# TW pretty name does not include the version
-	[ -n "$os_release_VERSION" ] || title="$title $os_release_VERSION_ID"
+	# [ -n "$os_release_VERSION" ] || title="$title $os_release_VERSION_ID"
 	# shellcheck disable=SC2154
 	sort_key="$os_release_ID"
 
@@ -529,7 +512,9 @@ install_kernel()
 	fi
 	if [ -z "$failed" ]; then
 		loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot.conf"
+		[ -n "$have_no_snapshots" ] && loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version.conf"
 		install_with_rollback "$tmpdir/entry.conf" "$loader_entry" || failed="bootloader entry"
+
 	fi
 	rm -f "$tmpdir/initrd"
 	rm -f "$tmpdir/entry.conf"
@@ -542,7 +527,7 @@ install_kernel()
 
 install_all_kernels()
 {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		local snapshot=""
 	else
 		local snapshot="${1:?}"
@@ -557,7 +542,7 @@ install_all_kernels()
 
 remove_all_kernels()
 {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		local snapshot=""
 	else
 		local snapshot="${1:?}"
@@ -630,18 +615,12 @@ list_entries()
 					fi
 				fi
 				if [ "$k" = 'options' ]; then
-					if [ $no_snapshots -eq 1 ]; then
-						local snapshot
-						read -r snapshot <<<"$(echo "$v" | sed -e "s,.*rootflags=subvol=${subvol_prefix}\([0-9]\+\),\1,")"
-						if [ -n "$v" ]; then
-							echo $snapshot
-						fi
-					else
-						local snapshot
-						read -r snapshot <<<"$(echo "$v" | sed -e "s,.*rootflags=subvol=${subvol_prefix}/.snapshots/\([0-9]\+\)/snapshot.*,\1,")"
-						if [ ! -d "/.snapshots/$snapshot/snapshot" ]; then
-							errors+=("/.snapshot/$snapshot/snapshot does not exist")
-						fi
+					[ -n "$have_no_snapshots" ] && break
+
+					local snapshot
+					read -r snapshot <<<"$(echo "$v" | sed -e "s,.*rootflags=subvol=${subvol_prefix}/.snapshots/\([0-9]\+\)/snapshot.*,\1,")"
+					if [ ! -d "/.snapshots/$snapshot/snapshot" ]; then
+						errors+=("/.snapshot/$snapshot/snapshot does not exist")
 					fi
 				fi
 			done < "$conf"
@@ -772,9 +751,7 @@ show_entry()
 
 list_snapshots()
 {
-	if [ $no_snapshots -eq 1 ]; then
-		err "list-snapshots incompatible with --no-snapshots!"
-	fi
+	[ -n "$have_no_snapshots"  ] && echo "System does no support snapshots." && exit 0
 	update_snapper 2>"$tmpfile" || err "$(cat "$tmpfile")"
 
 	local n=0
@@ -784,7 +761,7 @@ list_snapshots()
 		if [ "$isdefault" = "true" ]; then
 			id="\e[1;4m$id\e[m"
 		fi
-		update_kernels "${subvol_prefix}/.snapshots/$n/snapshot"
+		update_kernels "$n"
 		[ "$is_bootable" = 1 ] || id="!$id"
 		echo -e "$id $title"
 	done < <(jq '.root|.[]|[.number, .default, .description]|join(" ")' -r < "$snapperfile")
@@ -792,9 +769,7 @@ list_snapshots()
 
 show_snapper()
 {
-	if [ $no_snapshots -eq 1 ]; then
-		err "snapshots incompatible with --no-snapshots!"
-	fi
+	[ -n "$have_no_snapshots" ] && echo "System does does not supoort snapshots." && exit 0
 	if ! update_snapper 2>"$tmpfile"; then
 		d --title "Error" --textbox "$tmpfile" 0 0
 		exit 1
@@ -810,7 +785,7 @@ show_snapper()
 				default="$n"
 				title="\\Zb\Zu$title\\Zn"
 			fi
-			update_kernels "${subvol_prefix}/.snapshots/$n/snapshot"
+			update_kernels "$n"
 			[ "$is_bootable" = 1 ] || title="!$title"
 			list+=("$n" "$title")
 		done < <(jq '.root|.[]|[.number, .default, .description]|join(" ")' -r < "$snapperfile")
@@ -858,7 +833,7 @@ calc_chksum() {
 declare -A found_kernels
 find_kernels()
 {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		local subvol=""
 		subvol_prefix=""
 	else
@@ -868,7 +843,6 @@ find_kernels()
 	found_kernels=()
 
 	for fn in "${subvol#${subvol_prefix}}"/usr/lib/modules/*/"$image"; do
-		echo "fn: $fn"
 		kv="${fn%/*}"
 		kv="${kv##*/}"
 		calc_chksum "$fn"
@@ -886,20 +860,20 @@ declare -A stale_kernels
 is_bootable=
 update_kernels()
 {
-	if [ $no_snapshots -eq 1 ]; then
-		local subvol=""
+	if [ -n "$have_no_snapshots" ]; then
+		local snapshot=""
 	else
-		local subvol="${1:?}"
+		local snapshot="${1:?}"
 	fi
 	local path id
 	installed_kernels=()
 	stale_kernels=()
 	is_bootable=
-	find_kernels "$subvol"
+	find_kernels "$snapshot"
 	for kv in "${!found_kernels[@]}"; do
 		installed_kernels["/$entry_token/$kv/linux-${found_kernels[$kv]}"]=''
 	done
-	update_entries_for_subvol "$subvol"
+	update_entries_for_snapshot "$snapshot"
 
 	# XXX: maybe we should parse the actual path in the entry
 	while read -r path id; do
@@ -915,12 +889,12 @@ update_kernels()
 
 list_kernels()
 {
-	if [ $no_snapshots -eq 1 ]; then
-		subvol=""
+	if [ -n "$have_no_snapshots" ]; then
+		local snapshot=""
 	else
-		subvol="${subvol_prefix}/.snapshots/${1:?}/snapshot"
+		local snapshot="${1:?}"
 	fi
-	update_kernels "$subvol"
+	update_kernels "$snapshot"
 	local kernelfiles=("${!installed_kernels[@]}")
 	for k in "${kernelfiles[@]}"; do
 		# echo "k: $k"
@@ -943,8 +917,8 @@ list_kernels()
 
 is_bootable()
 {
-	subvol="${subvol_prefix}/.snapshots/${1:?}/snapshot"
-	update_kernels "$subvol"
+	local snapshot="${1:?}"
+	update_kernels "$snapshot"
 
 	[ "$is_bootable" = 1 ] || return 1
 	return 0
@@ -953,11 +927,11 @@ is_bootable()
 show_kernels()
 {
 	subvol="${subvol_prefix}/.snapshots/${1:?}/snapshot"
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		subvol=""
 	fi
 	while true; do
-		update_kernels "$subvol"
+		update_kernels "$snapshot"
 		local list=()
 		local n=0
 		local default=
@@ -1047,7 +1021,7 @@ is_installed()
 
 find_sdboot()
 {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		local prefix=""
 	else
 		local prefix="/.snapshots/${1-$root_snapshot}/snapshot"
@@ -1062,7 +1036,7 @@ find_sdboot()
 
 sdboot_needs_update()
 {
-	if [ no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		local prefix=""
 	else
 		local snapshot="${1-$root_snapshot}"
@@ -1082,7 +1056,7 @@ sdboot_needs_update()
 
 install_sdboot()
 {
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		# local snapshot="${1:-$root_snapshot}"
 		local prefix=""
 		
@@ -1137,7 +1111,7 @@ install_sdboot()
 	[ -s "$boot_root/loader/entries.srel" ] || echo type1 > "$boot_root/loader/entries.srel"
 
 	# echo "boot_root: $boot_root"
-	if [ $no_snapshots -eq 1 ]; then
+	if [ -n "$have_no_snapshots" ]; then
 		echo -e "timeout 5\n#console-mode keep\n" > "$boot_root/loader/loader.conf"
 	else
 		[ -e "$boot_root/loader/loader.conf" ] || echo -e "#timeout 3\n#console-mode keep\n" > "$boot_root/loader/loader.conf"
@@ -1532,7 +1506,6 @@ while true ; do
 		--no-reuse-initrd) arg_no_reuse_initrd=1; shift ;;
 		--no-random-seed) arg_no_random_seed=1; shift ;;
 		--all) arg_all_entries=1; shift ;;
-		--no-snapshots) no_snapshots=1; shift ;;
                 --) shift ; break ;;
                 *) echo "Internal error!" ; exit 1 ;;
         esac
@@ -1555,7 +1528,8 @@ done
 # XXX: bootctl should have json output for that too
 eval "$(bootctl 2>/dev/null | sed -ne 's/Firmware Arch: *\(\w\+\)/firmware_arch="\1"/p;s/ *token: *\(\w\+\)/entry_token="\1"/p;s, *\$BOOT: *\([^ ]\+\).*,boot_root="\1",p')"
 read -r root_uuid root_device < <(findmnt / -v -r -n -o UUID,SOURCE)
-if [ $no_snapshots -eq 1 ]; then
+if ! { [ "$(stat -f -c %T /)" = "btrfs" ] && [ -d /.snapshots ]; }; then
+	have_no_snapshots=1
 	root_subvol=""
 	sub_vol_prefix=""
 else
@@ -1572,7 +1546,7 @@ settle_entry_token
 
 [ -n "$boot_root" ] || err "No ESP detected. Legacy system?"
 [ -n "$root_uuid" ] || err "Can't determine root UUID"
-[ -n "$root_subvol" ] || [ $no_snapshots -eq 1 ] || err "Can't determine root subvolume"
+[ -n "$root_subvol" ] || [ -n "$have_no_snapshots" ] || err "Can't determine root subvolume"
 [ -n "$root_device" ] || err "Can't determine root device"
 [ -n "$entry_token" ] || err "No entry token. sd-boot not installed?"
 [ -n "$firmware_arch" ] || err "Can't determine firmware arch"
@@ -1582,7 +1556,7 @@ case "$firmware_arch" in
 	*) err "Unsupported architecture $firmware_arch" ;;
 esac
 
-if [ $no_snapshots -eq 1 ]; then
+if [ -n "$have_no_snapshots" ]; then
 	root_snapshot=""
 else
 	root_snapshot="${root_subvol#${subvol_prefix}/.snapshots/}"
