Install extra EFI binaries
Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/sdbootutil b/sdbootutil
--- a/sdbootutil
+++ b/sdbootutil
@@ -704,6 +704,11 @@ update_entries_for_this_system()
 	update_entries jq "[.[]|select(has(\"options\"))|select(.options|test(\"root=(?:$root)\"))]"
 }
 
+update_entries_for_extra()
+{
+	update_entries jq "[.[]|select((.linux//.efi//\"\")|startswith(\"/EFI/extra\"))]"
+}
+
 entry_conf_file()
 {
 	local kernel_version="${1:?}"
@@ -1981,6 +1986,106 @@ esp_root_drive_partno_dseq()
 	   ' < "$devicefile"
 }
 
+extra_entry_needs_update()
+{
+	local entry="$1"
+
+	# If we do not have a version in the entry file (or the entry
+	# file is missing), then we assume that an update is required
+	[ -n "$entry" ] || return 0
+	read -r _ nv < <(grep -ao '^version .*$' "$entry")
+	[ -n "$nv" ] || return 0
+
+	entry="${boot_root}/loader/entries/$(basename "$entry")"
+	[ -f "$entry" ] || return 0
+	read -r _ v < <(grep -ao '^version .*$' "$entry")
+	[ -n "$v" ] || return 0
+
+	systemd-analyze compare-versions "$v" "<" "$nv" 2> /dev/null
+}
+
+install_extra_entry()
+{
+	local subvol="$1"
+	local entry="$2"
+
+	local -A e
+	local -a l
+	while read -r line; do
+		[[ "$line" == '#'* ]] && continue
+		IFS="=" read -r -a l <<<"$line"
+		[ "${#l[@]}" -eq 2 ] || err "Cannot parse line $line"
+		e["${l[0]}"]="${l[1]}"
+	done < "$entry"
+
+	[ -n "${e[EFI]}" ] || return 0
+	[ -f "${subvol:1}${e[EFI]}" ] || err "Missing extra entry file ${e[EFI]}"
+	[ -z "${e[ENTRY]}" ] || [ -f "${subvol:1}${e[ENTRY]}" ] || err "Missing extra entry file ${e[ENTRY]}"
+
+	# If the file can be installed, echo the name so it can be
+	# registered as installed (even if does not needs to be
+	# updated)
+	echo "/EFI/extra/$(basename "${e[EFI]}")"
+
+	extra_entry_needs_update "${subvol:1}${e[ENTRY]}" || return 0
+
+	mkdir -p "${esp_root}/EFI/extra"
+	install -p -D "${subvol:1}${e[EFI]}" "${esp_root}/EFI/extra"
+	[ -z "${e[ENTRY]}" ] || install -p -D "${subvol:1}${e[ENTRY]}" "${boot_root}/loader/entries"
+}
+
+install_extra_entries()
+{
+	local snapshot="$1"
+
+	local subvol=""
+	[ -z "$have_snapshots" ] || subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
+
+	update_entries_for_extra
+
+	local efi install_extra_entry_status
+	local -A entries
+	for i in "${subvol:1}"/usr/lib/sdbootutil/entries.d/*.conf; do
+		[ -e "${subvol:1}/etc/sdbootutil/entries.d/$(basename "$i")" ] && continue
+		dbg_cat "$i"
+		efi="$(install_extra_entry "$subvol" "$i")"
+		install_extra_entry_status=$?
+		[ "$install_extra_entry_status" -eq 0 ] || {
+			warn "Error installing extra entry $(basename "$i")"
+		}
+		[ -z "$efi" ] || entries["$efi"]=1
+	done
+
+	for i in "${subvol:1}"/etc/sdbootutil/entries.d/*.conf; do
+		dbg_cat "$i"
+		efi="$(install_extra_entry "$subvol" "$i")"
+		install_extra_entry_status=$?
+		[ "$install_extra_entry_status" -eq 0 ] || {
+			warn "Error installing extra entry $(basename "$i")"
+		}
+		[ -z "$efi" ] || entries["$efi"]=1
+	done
+
+	# Remove the entry + efi pairs not installed
+	local entry
+	while read -r efi; do
+		read -r entry
+		[ -n "${entries[$efi]}" ] || {
+			rm -f "${esp_root}/EFI${efi}"
+			rm -f "$entry"
+		}
+	done < <(jq -r '.[] | .linux // .efi, .path' < "$entryfile")
+
+	# Finally, remove the single efi files not installed
+	for i in "${esp_root}"/EFI/extra/*; do
+		efi="${i#"${esp_root}"}"
+		[ "${entries[$efi]:-0}" -eq 1 ] || rm -f "${esp_root}${efi}"
+	done
+
+	# This action will require to update the PCR predictions
+	update_predictions=1
+}
+
 install_bootloader()
 {
 	local snapshot=""
@@ -2098,6 +2203,8 @@ bootloader_update()
 		info "The bootloader will be downgraded"
 		install_bootloader "${1:-$root_snapshot}"
 	fi
+
+	install_extra_entries "${1:-$root_snapshot}"
 }
 
 hex_to_binary()
@@ -4508,6 +4615,7 @@ fi
 case "$1" in
 	install)
 		install_bootloader "${2:-$root_snapshot}"
+		install_extra_entries "${2:-$root_snapshot}"
 		create_default_config_file ;;
 	needs-update)
 		bootloader_needs_update "${2:-$root_snapshot}" ;;
