Fix boot entry detection with(out) boot counting
We will now check if an entry for the current snapshot already exists
(with out without boot counting) and determine based on the file hash
if we want to reuse it. This way, we do not reset boot counting if
the content didn't change, but also reset it if it changed.
We will, however, never remove the boot counter from existing entries,
even if disabled.

diff --git a/sdbootutil b/sdbootutil
--- a/sdbootutil
+++ b/sdbootutil
@@ -1148,17 +1148,55 @@ install_kernel()
 			tries=
 		fi
 
-		# If the version without "tries" suffix is present, do
-		# not create a new one.  This avoid duplication, but
+		# If the version with or without "tries" suffix is present,
+		# do not create a new one.  This avoid duplication, but
 		# also doing this check so late give the chance of
 		# adding the kernel or initrd in case that the user
 		# removes them
-		local entry_name
+		local entry_name target_entry existing
 		entry_name="$(entry_conf_file "$kernel_version" "$snapshot")"
-		loader_entry="$(find "$boot_root/loader/entries" -maxdepth 1 -type f -name "${entry_name%.conf}+*" -print -quit)"
-		if [ -z "$loader_entry" ]; then
-			loader_entry="$boot_root/loader/entries/$(entry_conf_file "$kernel_version" "$snapshot" "$tries")"
-			install_with_rollback "$tmpdir/entry.conf" "$loader_entry" || failed="bootloader entry"
+		target_entry="$boot_root/loader/entries/$(entry_conf_file "$kernel_version" "$snapshot" "$tries")"
+
+		# Detect a (possibly) existing entry
+		# We assume at max one exists so far
+		existing="$(find "$boot_root/loader/entries" -maxdepth 1 -type f -name "${entry_name%.conf}*.conf" -print -quit)"
+
+		if [ -e "$existing" ]; then
+			# The old entry has the same content as the new one
+			# This will also be true if boot counting is active
+			# for the old entry, but disabled for the new one.
+			# We will not remove boot counters from existing
+			# entries.
+			if cmp -s "$tmpdir/entry.conf" "$existing"; then
+				info "Reusing $existing"
+			else
+				# Write new entry
+				# New entry and old entry have the same name
+				if [[ "$existing" == "$target_entry" ]]; then
+					install_with_rollback "$tmpdir/entry.conf" "$target_entry" || failed="bootloader entry"
+				else
+					# We can't use install_with_rollback since names differs
+					mv "$existing" "$existing.bak" || failed="bootloader entry"
+					if [ -z "$failed" ]; then
+						install -p -m 0644 "$tmpdir/entry.conf" "$target_entry" || failed="bootloader entry"
+						chown root:root "$target_entry" 2> /dev/null || :
+						info "Installed $target_entry"
+					fi
+					# We can't use the trap cleanup since names differ
+					if [ -z "$failed" ]; then
+						# This leftover file should not lead to a failed state
+						info "Removing $existing.bak"
+						rm -f "$existing.bak" || :
+					else
+						info "Restoring $existing.bak"
+						mv "$existing.bak" "$existing" || :
+						rm -f "$target_entry"
+					fi
+				fi
+			fi
+		else
+			# No existing entry: create the target entry
+			install_with_rollback "$tmpdir/entry.conf" "$target_entry" || failed="bootloader entry"
 		fi
 		rm -f "$tmpdir/entry.conf"
 	fi
